### PR TITLE
Add Semigroup instance if base >= 4.11

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by Gabriella439** [comment]
I recommend following the instructions here for maximum forward compatbility:

https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid#RecommendedVariant

I also have a separate pull request up to change the Travis build to switch to newer versions of GHC since those instructions only work for GHC 7.10 and later: #11

**Comment by mitchellwrosen** [comment]
Got it - I think I did that right

**Comment by Gabriella439** [comment]
Looks great!  Could you also merge `master` into your branch?  I just updated `.travis.yml` to test newer versions of GHC so that we don't have to add additional changes for GHC 7.8 or older

**Comment by Gabriella439** [comment]
Oh, and it looks like this passes for older versions of GHC anyway :)

**Comment by Gabriella439** [comment]
Then I'll go ahead and merge this since I'm reasonably sure it's correct

**Comment by mitchellwrosen** [comment]
Thank you sir! This type seems worthy of being in a "Haskell stdlib"-type package. I've started toying around with one here: http://mitchellwrosen.github.io/mitchell-stdlib/ - so thanks!

**Comment by Gabriella439** [comment]
I agree.  That's why I kept it as simple and dependency-free as possible :)

**Comment by Gabriella439** [comment]
Alright, this is now up on Hackage as `list-transformer-1.0.4`

**Pull request merged**
